name: Compile kernel a14-6-1

permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions
  
on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        # description: "Select KernelSU | Note: Select MKSU for the standard version"
        description: "Select KernelSU"
        required: true
        type: choice
        options:
          - Official
          - Next
          - MKSU
          - SukiSU
        default: SukiSU
      kernelsu_branch:
        description: "Select the ksu branch"
        required: true
        type: choice
        options:
          - Stable
          - Dev
          - Other
        default: Stable
      # kernelsu_branch_other:
      #   description: "If you selected "Other", specify your custom branch"
      #   required: false
      #   type: string  # This input is required if 'Other' is chosen
      version:
        description: 'Custom version name (e.g., if the characters after 6.1.93 are left blank, the default version number will be used)'
        required: false
        type: string
      build_time:
        description: 'Set kernel build time (format see repository description)'
        required: false
        type: string
      use_zram:
        description: 'Do you want to enable adding more ZRAM algorithms?'
        required: true
        type: boolean
        default: true
      use_bbg:
        description: 'Do you want to enable the BBG write-blocking patch? (Please close it if it reports an error)'
        required: true
        type: boolean
        default: true
      use_kpm:
        description: 'Do you want the KPM function enabled?'
        required: true
        type: boolean
        default: true
      get_manager:
        description: 'Get the latest KSU Manager and SUSFS modules?'
        required: true
        type: boolean
        default: true
      onlyAk3:
        description: 'Upload only AK3 compressed package? (No boot, faster download)'
        required: false
        type: boolean
        default: false

jobs:

  build-kernel-a14-6-1:
    uses: ./.github/workflows/kernel-a14-6.1.yml
    secrets: inherit
    with:
      make_release: false
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      version: ${{ inputs.version }}
      use_zram: ${{ inputs.use_zram }}
      use_bbg: ${{ inputs.use_bbg }}
      use_kpm: ${{ inputs.use_kpm }}
      onlyAk3: ${{ inputs.onlyAk3 }}
      build_time: ${{ inputs.build_time }}
  get-ksu-manager:
    if: ${{ inputs.get_manager }}
    uses: ./.github/workflows/get-manager.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernelsu_variant }}

